### ISSUE TITLE
Unable to generate client with RAML 1.0 and Libraries

### ISSUE THREAD

**Issue by ksubburayalu** [mulesoft-labs/raml-java-client-generator#14]
Hello, we are unable to generate client code using RAML 1.0 and libraries. Attached RAML file that causing issues. Initially I was getting "Unrecognized token 'yaml': was expecting ('true', 'false' or 'null')
 at [Source: [yaml-type-flag]; line: 1, column: 6]". Did a local update to pass the right typeDeclaration string in getTypeAsString class and passed the issue. The RAML uses the "uses" syntax and doesn't have "types" inline in the RAML. Because of that the "types" aren't recognized and using the examples to create the client classes. Updated the RAML to have inline "types" and now erroring out "com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input".  Still working on how to fix this issue.   

Can we get support for data types defined in library and using "uses" clause in RAML

**Comment by machaval** [comment]
I don't see the attached raml. Can you link it?

**Comment by ksubburayalu** [comment]
Attached the RAML 
[client-contracts (2).zip](https://github.com/mulesoft-labs/raml-java-client-generator/files/1825259/client-contracts.2.zip)

**Comment by machaval** [comment]
With latest version is working. Enjoy! :tada:

**Comment by machaval** [comment]
Just one comment types are not yet supported I will try to implement some basic stuff soon

**Comment by ksubburayalu** [comment]
Thanks Mariano. As noted types are not yet supported and generating same class with additional underscores (_).
