### ISSUE TITLE
Duplicate client constructor

### ISSUE THREAD

**Issue by ktmcgrat** [mulesoft-labs/raml-java-client-generator#24]
The following RAML will create java files with RamlJavaClientGenerator, but the client.java  contains a duplicate definition of TestClient()  function, one with null, and the other with the base uri.

#%RAML 1.0
title: test
baseUri: https://mulesoft.com
version: v1

/api/a:
    get:

/tmp/output/testapi/api/TestClient.java:23: error: constructor TestClient() is already defined in class TestClient
    public TestClient() {
           ^
1 error

The generated code contains:

public class TestClient {

    private String _baseUrl;
    public final Api api;

    public TestClient() {
        _baseUrl = null;
        api = null;
    }

   public TestClient(String baseUrl) {
        _baseUrl = baseUrl;
        api = new Api(getBaseUri(), getClient());
    }

    public TestClient() {
        this("https://mulesoft.com");
    }

**Comment by machaval** [comment]
Fixed !!!! Thanks
