### ISSUE TITLE
Please add java8 LocalDate/LocalTime/LocalDateTime support

### ISSUE THREAD

**Issue by etsybaev** [mulesoft-labs/raml-java-client-generator#30]
Please add java8 LocalDate/LocalTime/LocalDateTime support.
I.e. make generated POJO has java8 LocalDate/LocalTime/LocalDateTime types.

Thanks in advance!

**Comment by machaval** [comment]
I've just added a new property `useJava8Dates` So that this is possible. Also added `useOptionalForGetters`
