### ISSUE TITLE
Version 0.2 of raml-client-generator-maven-plugin is not available on maven?

### ISSUE THREAD

**Issue by hvm2hvm** [mulesoft-labs/raml-java-client-generator#36]
**Describe the bug**

I get "the POM for org.mule.raml.codegen:raml-client-generator-maven-plugin:jar:0.2 is missing, no dependency information available" when I run maven

**To Reproduce**
I added the following to my pom.xml file (exactly as in the github README):

    <build>
        <plugins>
            <plugin>
                <groupId>org.mule.raml.codegen</groupId>
                <artifactId>raml-client-generator-maven-plugin</artifactId>
                <version>0.2</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate-client</goal>
                        </goals>
                        <configuration>
                            <basePackage>org.mule.example</basePackage>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

I also added the repos I found in the pom.xml from the project

    <repositories>
        <repository>
            <id>mulesoft-releases</id>
            <name>Mule Release Repository</name>
            <url>https://repository.mulesoft.org/releases</url>
        </repository>
        <repository>
            <id>mulesoft-snapshots</id>
            <name>Mule Snapshot Repository</name>
            <url>https://repository.mulesoft.org/snapshots</url>
        </repository>
    </repositories>

in the pom.xml as well as trying 0.2-SNAPSHOT for the plugin version (instead of 0.2). Nothing seems to work.

**Expected behavior**
The plugin gets downloaded and added to project?

**Comment by hvm2hvm** [comment]
OK, I realised that I have to add this to the pom.xml:

    <pluginRepositories>
        <pluginRepository>
            <id>mulesoft-releases</id>
            <name>Mule Release Repository</name>
            <url>https://repository-master.mulesoft.org/nexus/content/repositories/releases</url>
        </pluginRepository>
    </pluginRepositories>

Some explanation about this in the README would help though.

**Comment by ullgren** [comment]
Agree that this can be clarified better in the README.md.
Your welcome to phrase a proposed change to improve the documentation either directly here in the ticket or via a PR to the project.

**Comment by hvm2hvm** [comment]
I don't know exactly how to do a PR but the change would be simple: adding this at the end of the readme.md file
```
Note: you must add the following in pom as well


```xml
    <pluginRepositories>
        <pluginRepository>
            <id>mulesoft-releases</id>
            <name>Mule Release Repository</name>
            <url>https://repository-master.mulesoft.org/nexus/content/repositories/releases</url>
        </pluginRepository>
    </pluginRepositories>
` ` `
```

(remove the spaces from the last set of back ticks, I couldn't add them otherwise)

**Comment by ullgren** [comment]
Thanks, I've created a pull request with the change.

You can read more about working with [forks](https://help.github.com/articles/working-with-forks/) and the [fork and pull development model](https://help.github.com/articles/about-collaborative-development-models/) in [this](https://help.github.com/articles/about-collaborative-development-models/) and the following github articles.

[Here](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/) is also a blog post that takes you through the steps to create a fork, create and push a change to your forked project and then create a PR.

Give it a go and the next contribution will list your name in the commit log :-)
