### ISSUE TITLE
Generation of @JsonAnyGetter additionalProperties not-working on pre 2.9.0 jackson servers.

### ISSUE THREAD

**Issue by gaganis** [mulesoft-labs/raml-java-client-generator#40]
Hello

We are using the generator and we have come upon the following problem. The generator is including a @JsonAnyGetter annotated getAdditionalProperties method for the POST bodies.

I have found that this feature has been introduced in jackson from version 2.9.0 but in our case we are trying to deploy our application to a wildfly server which provides us with jackson 2.8.9. In this case jackson is adding an empty additionalProperties to the outgoing JSON which is then rejected by the API we are trying to access.

Is it possible to disable the generation globally or per type of the additionalProperties field & accompanying methods.

Also any other ideas would be greatly appreciated!

Thanks!
Giorgos

**Comment by machaval** [comment]
Hi, I've just added a new property to avoid generating additionalProperties. So that may help. I was not able to see how to generate that in another way as we use a third party tool. [jsonschema2pojo](https://github.com/joelittlejohn/jsonschema2pojo)  If this is good for you just close the issue

**Comment by gaganis** [comment]
Hi @machaval, Thanks a lot for the quick response and implementation! 

The property has solved the issue we had thus I am closing this.
