### ISSUE TITLE
Version 0.10 is missing in Repo

### ISSUE THREAD

**Issue by ca-stefan-cordes** [mulesoft-labs/raml-java-client-generator#45]
Version 0.10 is released, 

![image](https://user-images.githubusercontent.com/50696194/61282946-94951800-a7bc-11e9-8964-6dab08f0d3fb.png)

but not in

https://repository-master.mulesoft.org/nexus/content/repositories/releases/org/mule/raml/codegen/raml-client-generator-maven-plugin/

![image](https://user-images.githubusercontent.com/50696194/61282917-82b37500-a7bc-11e9-8d74-d4662ce2a9eb.png)

**Comment by machaval** [comment]
Thanks, my deploy script failed and I didn't realized
