### ISSUE TITLE
Support for RAML 1.0 spec

### ISSUE THREAD

**Issue by vijayrcse** [mulesoft-labs/raml-java-client-generator#6]
Hi 

could you please advise whether raml-java-client-generator has support for RAML 1.0 spec ?
also when the release for 0.2 is expected ?

**Comment by ldebello** [comment]
Hi vijayrcse,

Currently, it has partial support for RAML 1.0 spec (It does not support custom types), if you find an issue , please report it and we can work on that. 
There is not an official roadmap so we work on-demand, we are using the client generator internally so as soon as we hit some limitation, we try to include it in the client generator.

Regards,
Luis

**Comment by vijayrcse** [comment]
thanks for the reply we will try the RAML 1.0 and let you know if we come across any blockers
