### ISSUE TITLE
NPE with date

### ISSUE THREAD

**Issue by rscadrde** [mulesoft-labs/raml-java-client-generator#7]
Please update raml-parser due to NPE

https://github.com/raml-org/raml-java-parser/issues/290

**Comment by machaval** [comment]
Updated to latest raml java parser should fixe this issue

**Comment by rscadrde** [comment]
With raml 1.0 it is
`type: date-only`
instead of
`type: date`

Verified it is generating now with 0.2-SNAPSHOT. Waiting for release....
