### ISSUE TITLE
Set timeout

### ISSUE THREAD

**Issue by rscadrde** [mulesoft-labs/raml-java-client-generator#8]
Currently timeout is infinite when the generated
```
    private Client getClient() {
        return ClientBuilder.newClient();
    }
```
is called.

Please generate
```
	private Client getClient() {
		return ClientBuilder.newClient(createConfiguration());
	}

	protected Configuration createConfiguration() {
		return new ClientConfig();
	}

```
with a configurable configuration.

see http://www.adam-bien.com/roller/abien/entry/setting_timeout_for_the_jax

**Comment by xdarklight** [comment]
Hi @rscadrde,

can you please have a look at a00d042be32288d9e50c1968e0ca09f05d26885e and close this issue if you consider it fixed?
@ingmr's change allows you to configure the timeouts now (and SSL context, and all the other features supported by http://docs.oracle.com/javaee/7/api/javax/ws/rs/client/ClientBuilder.html )

**Comment by rscadrde** [comment]
Thank you.
  `JMethod getClient = containerClass.method(JMod.PROTECTED, Client.class, "getClient");`
looks good.
